In [2]:
import numpy as np

<img src="Datasets/2020-01-28_03-56-32-433698fdb6cb595d61a490062cd00619.png" width=700px/>

<h2>Datatypes and Attributes</h2>

<h3>Introducing n-dimensional Arrays</h3>

In [3]:
a1=np.array([1,2,3])
a2=np.array([[1,2,3],[4,5,6]])
a3=np.array([
            [[1,2,3],[4,5,6]],
            [[7,8,9],[10,11,12]],
            [[13,14,15],[16,17,18]]
            ])

In [4]:
a1

array([1, 2, 3])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3.shape

(3, 2, 3)

In [8]:
a3.dtype

dtype('int64')

In [9]:
type(a3)

numpy.ndarray

In [10]:
import pandas as pd
df=pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

<h3>Creating Arrays using NumPY</h3>

In [11]:
ones = np.ones((3,3,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [12]:
z=np.zeros((3,3,3))
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
range_arr=np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [14]:
np.random.seed(7)
random_arr=np.random.randint(0,10,(2,3))
random_arr

array([[4, 9, 6],
       [3, 3, 7]])

In [15]:
rand_arr=np.random.rand(3,5)
rand_arr

array([[0.45558491, 0.30801277, 0.26387084, 0.08674343, 0.41937221],
       [0.01591036, 0.52776479, 0.86880146, 0.33083925, 0.39294231],
       [0.67433042, 0.67231727, 0.69403158, 0.34597294, 0.92952819]])

Numbers are not actually random

In [16]:
np.random.seed(7)
random_arr=np.random.randint(0,10,(2,3))
random_arr

array([[4, 9, 6],
       [3, 3, 7]])

<h2>Viewing Arrays and Matrices</h2>

In [17]:
np.unique(random_arr)

array([3, 4, 6, 7, 9])

In [18]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [19]:
a3.shape

(3, 2, 3)

In [20]:
a3[1,1,:]

array([10, 11, 12])

<h2>Manipulating and Comparing arrays</h2>

<h3>Arithmetic</h3>

In [21]:
a1*a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [22]:
a2*a3


array([[[  1,   4,   9],
        [ 16,  25,  36]],

       [[  7,  16,  27],
        [ 40,  55,  72]],

       [[ 13,  28,  45],
        [ 64,  85, 108]]])

In [23]:
np.log2(a2)

array([[0.        , 1.        , 1.5849625 ],
       [2.        , 2.32192809, 2.5849625 ]])

Basically we can use arithmetic operations on numpy arrays

<h3>Aggregation Funtions</h3>
<small>Use Numpy's functions for numpy datatypes</small>

In [24]:
massive_arrays=np.random.random(100000)
massive_arrays[:10]

array([0.45558491, 0.30801277, 0.26387084, 0.08674343, 0.41937221,
       0.01591036, 0.52776479, 0.86880146, 0.33083925, 0.39294231])

In [25]:
%timeit np.sum(massive_arrays)
%timeit sum(massive_arrays)


44 µs ± 813 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
16.3 ms ± 2.58 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


more aggregation functions may include `mean,max,min,standard deviation,variance`</br>
<b>numpy functions are way more optimized than standard python functions</b> 

`Standard Deviation`: The Standard Deviation is a measure of how spread out numbers are. Its symbol is σ.

`Variance`: The average of the squared differences from the Mean.

In [26]:
np.std(a2)

1.707825127659933

In [27]:
np.var(a2)

2.9166666666666665

<h3>Reshaping and Transposing</h3>

In [28]:
a233=np.random.rand(2,3,3)
a233

array([[[0.23336169, 0.67484975, 0.87879333],
        [0.81652219, 0.79518218, 0.88273206],
        [0.91585275, 0.25894333, 0.30351642]],

       [[0.25257092, 0.53207836, 0.44413663],
        [0.49701842, 0.12486269, 0.20175668],
        [0.9155747 , 0.02582151, 0.76553632]]])

In [29]:
#a2*a233

In [30]:
a2=a2.reshape((2,3,1))

In [31]:
a2*a233

array([[[0.23336169, 0.67484975, 0.87879333],
        [1.63304439, 1.59036436, 1.76546412],
        [2.74755824, 0.77683   , 0.91054927]],

       [[1.01028368, 2.12831344, 1.77654653],
        [2.48509208, 0.62431344, 1.00878338],
        [5.49344817, 0.15492908, 4.59321791]]])

In [32]:
a3.T

array([[[ 1,  7, 13],
        [ 4, 10, 16]],

       [[ 2,  8, 14],
        [ 5, 11, 17]],

       [[ 3,  9, 15],
        [ 6, 12, 18]]])

In [33]:
np.random.seed(7)
mat1=np.random.randint(10,size=(5,3))
mat2=np.random.randint(10,size=(5,3))
mat1

array([[4, 9, 6],
       [3, 3, 7],
       [7, 9, 7],
       [8, 9, 8],
       [7, 6, 4]])

In [34]:
mat2

array([[0, 7, 0],
       [7, 6, 3],
       [5, 8, 8],
       [7, 5, 0],
       [0, 2, 8]])

<img src="Datasets/Screenshot from 2022-01-24 18-45-52.png" width=700px/>

In [35]:
#np.dot(mat1,mat2)

In [36]:
np.dot(mat1,mat2.T)

array([[ 63, 100, 140,  73,  66],
       [ 21,  60,  95,  36,  62],
       [ 63, 124, 163,  94,  74],
       [ 63, 134, 176, 101,  82],
       [ 42,  97, 115,  79,  44]])

In [37]:
np.random.seed(0)
weekly_sales_mat=np.random.randint(20,size=(5,3))
weekly_sales_mat

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [38]:
price_mat=np.array([10,8,12])
price_mat=price_mat.reshape((1,3))

In [39]:
sales=pd.DataFrame(weekly_sales_mat,index=["mon","tue","wed","Thu","Fri"],columns=["Almond Butter","peanut butter","cashew butter"])
sales

Almond Butter  peanut butter  cashew butter
mon             12             15              0
tue              3              3              7
wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [40]:
price=pd.DataFrame(price_mat,index=["price"],columns=["Almond Butter","peanut butter","cashew butter"])
price

Almond Butter  peanut butter  cashew butter
price             10              8             12

In [41]:
total_mat=np.dot(weekly_sales_mat,price_mat.T)
total_mat

array([[240],
       [138],
       [458],
       [232],
       [142]])

In [42]:
sales["total($)"]=total_mat

In [43]:
sales

Almond Butter  peanut butter  cashew butter  total($)
mon             12             15              0       240
tue              3              3              7       138
wed              9             19             18       458
Thu              4              6             12       232
Fri              1              6              7       142

we can use comparision operators on arrays

In [47]:
np.random.seed(0)
to_sort=np.random.randint(20,size=(3,3))
to_sort


array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18]])

In [48]:
np.sort(to_sort)

array([[ 0, 12, 15],
       [ 3,  3,  7],
       [ 9, 18, 19]])

In [49]:
np.argsort(to_sort)

array([[2, 0, 1],
       [0, 1, 2],
       [0, 2, 1]])

In [53]:
np.argmax(to_sort)

7

<img src="images/ishaq.jpg" height=500px/>

In [54]:
from matplotlib.image import imread
ishaq=imread("images/ishaq.jpg")
type(ishaq)

numpy.ndarray

In [58]:
ishaq.shape

(1024, 768, 3)

In [64]:
ishaq[:10,:5,:]

array([[[228, 220, 197],
        [228, 220, 197],
        [228, 220, 197],
        [228, 220, 197],
        [228, 220, 197]],

       [[230, 222, 199],
        [230, 222, 199],
        [230, 222, 199],
        [230, 222, 199],
        [230, 222, 199]],

       [[230, 222, 199],
        [230, 222, 199],
        [230, 222, 199],
        [230, 222, 199],
        [230, 222, 199]],

       [[227, 219, 196],
        [227, 219, 196],
        [227, 219, 196],
        [227, 219, 196],
        [227, 219, 196]],

       [[227, 219, 196],
        [227, 219, 196],
        [227, 219, 196],
        [227, 219, 196],
        [227, 219, 196]],

       [[229, 221, 198],
        [229, 221, 198],
        [229, 221, 198],
        [229, 221, 198],
        [229, 221, 198]],

       [[228, 220, 197],
        [228, 220, 197],
        [228, 220, 197],
        [228, 220, 197],
        [228, 220, 197]],

       [[226, 218, 195],
        [226, 218, 195],
        [226, 218, 195],
        [226, 218, 195],
        [22